# Generated by Django 2.0.6 on 2018-06-12 15:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PodcastName', models.CharField(max_length=140, null=True)),
                ('PodcastAuthor', models.CharField(max_length=20, null=True)),
                ('PodcastDesc', tinymce.models.HTMLField(null=True, verbose_name='')),
                ('PodcastBackgroundImage', models.FileField(null=True, upload_to='thumbnails/')),
                ('PodcastEpisodeCount', models.IntegerField(null=True)),
                ('PodcastListenTime', models.BigIntegerField(null=True)),
                ('PodcastSlug', models.SlugField(blank=True, default='no-slug', max_length=100)),
            ],
        ),
    ]
