# Generated by Django 2.0.6 on 2018-06-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='PodcastAuthor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='PodcastBackgroundImage',
            new_name='Background_Image',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='PodcastDesc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='PodcastEpisodeCount',
            new_name='Episode_Count',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='PodcastName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='PodcastSlug',
            new_name='Slug',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='PodcastListenTime',
            new_name='Total_Listen_Time',
        ),
    ]
