# Generated by Django 2.0.6 on 2018-06-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0002_auto_20180612_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='Created_Date',
            field=models.IntegerField(null=True),
        ),
    ]
