# Generated by Django 2.0.6 on 2018-06-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0003_podcast_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='Slug',
            new_name='slug',
        ),
    ]
