# Generated by Django 2.0.6 on 2018-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0004_auto_20180613_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='Created_Date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='Description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
