# Generated by Django 2.0.6 on 2018-06-13 13:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0005_auto_20180613_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, null=True)),
                ('Date_Of_Publication', models.DateTimeField(editable=False, null=True)),
                ('Last_Updated_At', models.DateTimeField(null=True)),
                ('Episode_Description', tinymce.models.HTMLField(null=True, verbose_name='')),
                ('Episode_File', models.FileField(null=True, upload_to='Episode_File/')),
                ('Episode_Thumbnail', models.FileField(null=True, upload_to='Episode_Thumbnails/')),
                ('Created_By_User', models.CharField(max_length=140, null=True)),
                ('Number_of_Views', models.BigIntegerField(null=True)),
                ('Number_Of_Likes', models.IntegerField(null=True)),
                ('epi_slug', models.SlugField(blank=True, default='no-slug', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='Created_By_User',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='Background_Image',
            field=models.FileField(null=True, upload_to='Podcast_Thumbnails/'),
        ),
    ]
