# Generated by Django 2.0.6 on 2018-06-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0006_auto_20180613_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='Pod_Slug',
            field=models.SlugField(blank=True, default='no-slug', max_length=300),
        ),
    ]
