# Generated by Django 2.0.6 on 2018-06-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0007_episode_pod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Podcast.Podcast'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='epi_slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
    ]
