# Generated by Django 2.0.6 on 2018-06-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0009_remove_episode_podcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='epi_slug',
        ),
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, default='no-slug', max_length=300),
        ),
    ]
