# Generated by Django 2.0.6 on 2018-06-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0010_auto_20180614_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='slug',
            new_name='Episode_Slug',
        ),
    ]
